### ISSUE TITLE
update F5 BigIP LTM requirements in README

### ISSUE THREAD

**Issue by ophiion** [F5Networks/tf-bigip-version0.12#10]
Can we update the F5 BigIP LTM requirements in the readme to reflect the right process and TMOS versions.   

Current readme: 
F5 BigIP LTM requirements
This provider uses the iControlREST API, make sure that it is installed and enabled on your F5 device before proceeding.
All the resources are validated with BigIP v12.1.1

Cloud docs captures it better:
https://clouddocs.f5.com/products/orchestration/terraform/latest/

**Comment by focrensh** [comment]
Looks like this was done, but missed closing the issue.

https://github.com/F5Networks/terraform-provider-bigip#f5-bigip-ltm-requirements
