### ISSUE TITLE
make build failed

### ISSUE THREAD

**Issue by fwissue** [F5Networks/tf-bigip-version0.12#14]
mliu-7293:terraform-provider-bigip mliu$ make build
==> Checking that code complies with gofmt requirements...
go install
go: downloading github.com/hashicorp/terraform v0.12.0
go: downloading github.com/f5devcentral/go-bigip v0.0.0-20190813232614-cb399c531a76
go: extracting github.com/f5devcentral/go-bigip v0.0.0-20190813232614-cb399c531a76
go: extracting github.com/hashicorp/terraform v0.12.0
go: downloading github.com/hashicorp/go-plugin v1.0.1-0.20190430211030-5692942914bb
go: downloading google.golang.org/grpc v1.19.0
go: downloading github.com/hashicorp/go-hclog v0.7.0
go: downloading github.com/hashicorp/hcl v1.0.0
go: extracting github.com/hashicorp/go-plugin v1.0.1-0.20190430211030-5692942914bb
go: extracting github.com/hashicorp/go-hclog v0.7.0
go: downloading github.com/hashicorp/hil v0.0.0-20190212132231-97b3a9cdfa93
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: extracting github.com/hashicorp/hcl v1.0.0
go: extracting github.com/hashicorp/hil v0.0.0-20190212132231-97b3a9cdfa93
go: extracting google.golang.org/grpc v1.19.0
go: extracting github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/hashicorp/yamux v0.0.0-20181012175058-2f1d1f20f75d
go: downloading github.com/google/go-cmp v0.2.0
go: extracting github.com/hashicorp/yamux v0.0.0-20181012175058-2f1d1f20f75d
go: extracting github.com/google/go-cmp v0.2.0
go: downloading google.golang.org/genproto v0.0.0-20190306203927-b5d61aea6440
go: extracting google.golang.org/genproto v0.0.0-20190306203927-b5d61aea6440
go: finding github.com/hashicorp/terraform v0.12.0
go: finding github.com/f5devcentral/go-bigip v0.0.0-20190813232614-cb399c531a76
go: finding github.com/hashicorp/go-hclog v0.7.0
go: finding github.com/hashicorp/hil v0.0.0-20190212132231-97b3a9cdfa93
go: finding github.com/hashicorp/hcl v1.0.0
go: finding github.com/hashicorp/go-plugin v1.0.1-0.20190430211030-5692942914bb
go: finding github.com/google/go-cmp v0.2.0
go: finding github.com/mitchellh/go-homedir v1.1.0
go: finding google.golang.org/genproto v0.0.0-20190306203927-b5d61aea6440
go: finding google.golang.org/grpc v1.19.0
go: finding github.com/hashicorp/yamux v0.0.0-20181012175058-2f1d1f20f75d
# github.com/terraform-providers/terraform-provider-bigip/bigip
bigip/resource_bigip_ltm_virtual_server.go:424:5: vs.Disabled undefined (type *bigip.VirtualServer has no field or method Disabled)
bigip/resource_bigip_ssl_certificate.go:50:15: client.UploadCertificate undefined (type *bigip.BigIP has no field or method UploadCertificate)
bigip/resource_bigip_ssl_certificate.go:71:28: client.GetCertificate undefined (type *bigip.BigIP has no field or method GetCertificate)
bigip/resource_bigip_ssl_certificate.go:87:28: client.GetCertificate undefined (type *bigip.BigIP has no field or method GetCertificate)
bigip/resource_bigip_ssl_certificate.go:107:15: client.UpdateCertificate undefined (type *bigip.BigIP has no field or method UpdateCertificate)
bigip/resource_bigip_ssl_certificate.go:121:15: client.DeleteCertificate undefined (type *bigip.BigIP has no field or method DeleteCertificate)
bigip/resource_bigip_ssl_key.go:50:15: client.UploadKey undefined (type *bigip.BigIP has no field or method UploadKey)
bigip/resource_bigip_ssl_key.go:65:24: client.GetKey undefined (type *bigip.BigIP has no field or method GetKey)
bigip/resource_bigip_ssl_key.go:79:24: client.GetKey undefined (type *bigip.BigIP has no field or method GetKey)
bigip/resource_bigip_ssl_key.go:99:15: client.UpdateKey undefined (type *bigip.BigIP has no field or method UpdateKey)
bigip/resource_bigip_ssl_key.go:99:15: too many errors
make: *** [build] Error 2

**Comment by papineni87** [comment]
I am build the repo without any issues.

root@terraforn-ubuntu3:~/go/src/github.com/terraform-providers# git clone https://github.com/F5Networks/terraform-provider-bigip.git
Cloning into 'terraform-provider-bigip'...
remote: Enumerating objects: 100, done.
remote: Counting objects: 100% (100/100), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 13892 (delta 44), reused 58 (delta 23), pack-reused 13792
Receiving objects: 100% (13892/13892), 77.74 MiB | 38.38 MiB/s, done.
Resolving deltas: 100% (8009/8009), done.
Checking connectivity... done.
root@terraforn-ubuntu3:~/go/src/github.com/terraform-providers# 
root@terraforn-ubuntu3:~/go/src/github.com/terraform-providers# cd terraform-provider-bigip
root@terraforn-ubuntu3:~/go/src/github.com/terraform-providers/terraform-provider-bigip# ls -a
.  ..  .git  .gitignore  .go-version  .goreleaser.yml  .travis.yml  CHANGELOG.md  GNUmakefile  Gopkg.lock  Gopkg.toml  LICENSE  README.md  bigip  docs  examples  go.mod  go.sum  main.go  scripts  support.md  vendor  website

root@terraforn-ubuntu3:~/go/src/github.com/terraform-providers/terraform-provider-bigip# make build
==> Checking that code complies with gofmt requirements...
go install
root@terraforn-ubuntu3:~/go/src/github.com/terraform-providers/terraform-provider-bigip#

**Comment by fwissue** [comment]
mliu-7293:~ mliu$ go version
go version go1.13.4 darwin/amd64

platform: mac

mliu-7293:~ mliu$ terraform -v
Terraform v0.12.13

**Comment by RavinderReddyF5** [comment]
@fwissue 
This is because of Vendor modules,
By default, go commands like go build ignore the vendor directory when in module mode

Can you please  set ```export GOFLAGS=-mod=vendor``` and run make build.

**Comment by fwissue** [comment]
Thanks that fixed the issue

**Comment by codygreen** [comment]
@RavinderReddyF5 - can we add this to the readme file?  I ran into the same issue and it seems like this should be a default setting when working with the provider.  

Thanks!

**Comment by RavinderReddyF5** [comment]
@codygreen sure will updated README file to reflect same.
