### ISSUE TITLE
AWS example needs to be updated

### ISSUE THREAD

**Issue by jperez3** [F5Networks/tf-bigip-version0.12#15]
while trying to provision via the AWS example, I got the terraform error:

`aws_instance.SCS_F5: Error launching source instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=atsce2p2dddau7yx2sha4hlsi`

When I click through to the link, I see: `This version has been removed and is no longer available to new customers.`

**Comment by RavinderReddyF5** [comment]
AMI provided in examples is pretty old, Updated with New AMI ID, can you please try now Deploying BIGIP VE in AWS.

**Comment by jperez3** [comment]
That worked, I was able to provision via the supplied AMI
