### ISSUE TITLE
AWS Example tries to rebuild EC2 instances after every apply

### ISSUE THREAD

**Issue by jperez3** [F5Networks/tf-bigip-version0.12#16]
It looks like there is something going on with the security groups when provisioning ec2 instances. After the initial apply, it will continue to ask to rebuild the instances every time because security group "changes"

eg.:

```
-/+ aws_instance.SCS_appserver2 (new resource required)
      id:                                        "i-xxxxxxxxxxxxxxxxxx" => <computed> (forces new resource)
      ami:                                       "ami-9be6f38c" => "ami-9be6f38c"
      arn:                                       "arn:aws:ec2:us-east-1:7xxxxxxxxxxxxx:instance/i-xxxxxxxxxxxxxxxxxx => <computed>
      security_groups.#:                         "0" => "1" (forces new resource)
      security_groups.xxxxxxxxxxxxx:                "" => "xxxxxxxxxxxxx" (forces new resource)
```

I checked the aws console and it looks like the security group is already attached.

version info:

```
$ terraform --version
Terraform v0.11.13
+ provider.aws v2.35.0
```

**Comment by papineni87** [comment]
It looks like AWS issue, let me try running plan and confirm it

**Comment by jperez3** [comment]
@papineni87 were you able to test/verify this issue?

**Comment by focrensh** [comment]
This workflow is around the aws resource. If you are still experiencing this issue, please open an issue for that provider.
