### ISSUE TITLE
build ssl profile

### ISSUE THREAD

**Issue by fwissue** [F5Networks/tf-bigip-version0.12#17]
Hello:

 Is there any Terraform command to build SSL profile with key/cert/intermedia certs? I don't see it here
https://www.terraform.io/docs/providers/bigip/r/bigip_sys_provision.html

Thanks,

~Mike

**Comment by RavinderReddyF5** [comment]
@fwissue 
Currently ssl profile resource module not available, it is under development, it will be available in next release. if need urgently we can release patch release with that feature.

**Comment by RavinderReddyF5** [comment]
@fwissue 
Can you please try validating your scenario with referring from docs below by local binary creation.
https://www.terraform.io/docs/providers/bigip/r/bigip_ltm_profile_client_ssl.html
https://www.terraform.io/docs/providers/bigip/r/bigip_ltm_profile_server_ssl.html

**Comment by papineni87** [comment]
This was fixed in the 1.1.0 release. If you are still having a problem with that release, please reopen this issue or file a new one.
