### ISSUE TITLE
having trouble logging into f5

### ISSUE THREAD

**Issue by jperez3** [F5Networks/tf-bigip-version0.12#18]
https://github.com/F5Networks/terraform-provider-bigip/blob/1fd6b70ffcd7bef1462ae3334ef9abe9df54e84b/examples/aws/userdata.sh#L88

I tried to use the password referenced in the user-data script, but I cannot log into the web interface, what are the default credentials to login?

**Comment by papineni87** [comment]
what is the bigip version you are using ? if it is v12.0/v13.0 default credentials are admin/admin but if it is v14/v15 we have to reset default passwords even for first time users

**Comment by jperez3** [comment]
I'm using the version provided in the example, believe it's `15.0.1-0.0.11` from `ami-03b18799f246d2695`

**Comment by jperez3** [comment]
@papineni87 how do I move forward with the password reset for the aws example in this repo?

**Comment by papineni87** [comment]
Can you try accessing bigip cli with admin as user, and change password. 
Login to bigip web interface with new password.

The scripts are written for bigip versions below v14.x, for v14 and above we cannot login bigip interface directly with admin without modifying it from cli.

I have tested it now with bigip v15 and able to login bigip web interface only after modifying it from cli

**Comment by papineni87** [comment]
root@terraforn-ubuntu3:~/go/src/github.com/terraform-providers/terraform-provider-bigip/examples/aws# ssh -i /root/.ssh/id_rsa admin@x.x.x.x
admin@(ip-10-0-0-10)(cfg-sync Standalone)(Active)(/Common)(tmos)# 
admin@(ip-10-0-0-10)(cfg-sync Standalone)(Active)(/Common)(tmos)# modify auth user admin password xxxxx
admin@(ip-10-0-0-10)(cfg-sync Standalone)(Active)(/Common)(tmos)# 
admin@(ip-10-0-0-10)(cfg-sync Standalone)(Active)(/Common)(tmos)#

**Comment by jperez3** [comment]
@papineni87 and anyone else who is encounters this in the future. I was able to ssh into the host by using the public key I used while provisioning the F5 appliance and the public IP that was output as `SCS_F5public_ip` after the `terraform apply` 

I used the method above to reset the `admin` user password and reached the f5 web interface via https://public_ip_goes_here 

I also tried adding a role/profile to enable AWS SSM console access, but it doesn't look like this is available via the provided AMI.
