### ISSUE TITLE
[doc] DO module - mistake in documentation

### ISSUE THREAD

**Issue by nmenant** [F5Networks/tf-bigip-version0.12#25]
https://www.terraform.io/docs/providers/bigip/r/bigip_do.html
 
“tenant_name - (Required) This is the partition name where the application services will be configured.”

Do doesn’t deal with application services. It handles the bigip base configuration(licensing, networking, clustering,...) 
it would be good to update this definition

**Comment by papineni87** [comment]
This is same as #24 , we will  fix the issue and update the documentation also.

**Comment by papineni87** [comment]
@nmenant we have provided fix for this, can you try using the bigip provider with the latest code now.
