### ISSUE TITLE
[AS3/DO] tenant_name parameter

### ISSUE THREAD

**Issue by nmenant** [F5Networks/tf-bigip-version0.12#26]
In the terraform AS3 and DO modules, we ask for a specific parameter called tenant_name. The challenge here is that customer may work on a declaration that involves several tenants/partitions at the same time. This may confuse customers on how to use this specific parameter. 

It would be good to understand how this parameter is leveraged and how it could impact a declaration with multiple tenants in it. It is probably worth documenting in more details

**Comment by papineni87** [comment]
This issue will be addressed with #24
