### ISSUE TITLE
DO Error on Terraform destroy

### ISSUE THREAD

**Issue by codygreen** [F5Networks/tf-bigip-version0.12#43]
When trying to tear down a BIG-IP I receive the following error:

```
terraform destroy --auto-approve
bigip_do.do-example: Refreshing state... [id=as3_test]
bigip_do.do-example: Destroying... [id=as3_test]

Error: Delete method on DO is not supported
```

This is a BIG-IP created via Terraform and configured via the DO and AS3 resources.  While DO technically doesn't need to do anything on a destroy it still needs to gracefully pass w/o an error.

**Comment by focrensh** [comment]
The resource now cleans up state but takes no action against the BIG-IP.
