### ISSUE TITLE
BIG-IQ Licensing

### ISSUE THREAD

**Issue by codygreen** [F5Networks/tf-bigip-version0.12#44]
We need a resource that can pull a license from BIG-IQ on BIG-IP creation and return the license to BIG-IQ upon BIG-IP deletion.  This is a requirement for a large Azure customer doing IaC.

While this can be done through a local-exec provisioner today we need to have this as a 1st class resource.

**Comment by focrensh** [comment]
First iterations of this capability were introduced in this resource: (1.2 release)
https://www.terraform.io/docs/providers/bigip/r/bigip_common_license_manage_bigiq.html

You must treat the license checked out as an object and it is not currently tied to the big-ip resource itself. This could be added within a workflow/module.
