### ISSUE TITLE
The provider provider.bigip does not support resource type "bigip_command".

### ISSUE THREAD

**Issue by svillegas-flores** [F5Networks/tf-bigip-version0.12#63]
$ terraform -v
Terraform v0.12.24
+ provider.bigip v1.1.2

**Comment by papineni87** [comment]
I guess it is recently merged in master branch , not released  in v1.1.2. It will be coming in new release, but in meantime we can clone from master branch and use the resource

**Comment by focrensh** [comment]
Tracked with TER-119. Release in provider 1.2.

https://www.terraform.io/docs/providers/bigip/r/bigip_command.html
