### ISSUE TITLE
Documentation Link on readme.md 

### ISSUE THREAD

**Issue by kreynoldsf5** [F5Networks/tf-bigip-version0.12#85]
The documentation link on the readme.md points to:
[https://github.com/F5Networks/terraform-provider-bigip/blob/master/website/docs](https://github.com/F5Networks/terraform-provider-bigip/blob/master/website/docs).

This is just a directory in the repo. I believe this link should point to the cloud docs page [here](https://clouddocs.f5.com/products/orchestration/terraform/latest/).

**Comment by papineni87** [comment]
Yep, needs to update the docs link to either clouddocs or terraform-bigip-provider docs ( https://www.terraform.io/docs/providers/bigip/index.html )

**Comment by focrensh** [comment]
Thanks, we will get this (and a few other items) updated under TER-367

**Comment by papineni87** [comment]
Fixed in v1.2.1, if issue seems to persist please reopen the issue
